# Generated by Django 2.2.2 on 2019-08-08 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dexmart/carousel_item')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=30)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdata', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateid', models.IntegerField()),
                ('updatedesc', models.CharField(max_length=200)),
                ('updatetime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('subcate', models.CharField(max_length=100)),
                ('pubdate', models.DateField()),
                ('description', models.BooleanField(default=False)),
                ('desc', models.TextField(blank=True)),
                ('keyfeatures', models.BooleanField(default=True)),
                ('feature', models.TextField(blank=True)),
                ('toprated', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='dexmart/prod_img')),
                ('deliveryby', models.DateField()),
                ('rating', models.FloatField(choices=[(2.5, 2.5), (2.8, 2.8), (3.4, 3.4), (3.5, 2.5), (4.2, 4.2), (4.4, 4.4), (4.6, 4.6), (4.8, 4.8), (4.9, 4.9)], default='')),
                ('brand', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('stock', models.BooleanField(default=True)),
                ('prodimg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dexmart/prod_img')),
                ('imgtext', models.TextField(default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dexmart.Product')),
            ],
        ),
    ]
